
name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.0' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet build ConversaoPeso.Web
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./ConversaoPeso.Web
          file: ./ConversaoPeso.Web/Dockerfile
          push: true
          tags: |
            cmcirilo/conversao-peso:latest
            cmcirilo/conversao-peso:${{ github.run_number }}
            
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps: 
     - uses: actions/checkout@v2
       
     - name: Kubernetes set context
       uses: Azure/k8s-set-context@v1.1
       with:
         method: kubeconfig
         kubeconfig: ${{ secrets.K8S_KUBECONFIG }}
         
     - name: Deploy to Kubernetes cluster
       uses: Azure/k8s-deploy@v1.3
       with: 
         images: cmcirilo/conversao-peso:${{ github.run_number }} 
         manifests: |
           deployment.yaml   
           
      


     
